---
sidebar: sidebar 
permalink: concept-onprem-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet, subscriptios, licenses, bluexp 
summary: Puede administrar los clústeres ONTAP que se ejecutan en controladores AFF/ FAS y ONTAP Select desde la consola de NetApp .  Agregar sistemas ONTAP locales a la consola de NetApp le permite administrar todos sus activos de almacenamiento y datos desde una única interfaz. 
---
= Obtenga información sobre la gestión de clústeres ONTAP locales en la consola de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede administrar los clústeres ONTAP que se ejecutan en controladores AFF/ FAS y ONTAP Select desde la consola de NetApp .  Agregar sistemas ONTAP locales a la consola le permite administrar de manera centralizada todos sus activos de almacenamiento y datos.



== Consola de NetApp

La consola de NetApp proporciona una gestión centralizada de los servicios de datos y almacenamiento de NetApp en entornos locales y en la nube a nivel empresarial. La consola es necesaria para acceder y utilizar los servicios de datos de NetApp . Como interfaz de administración, le permite administrar muchos recursos de almacenamiento desde una sola interfaz. Los administradores de la consola pueden controlar el acceso al almacenamiento y los servicios para todos los sistemas dentro de la empresa.

No necesita una licencia o suscripción para comenzar a usar NetApp Console y solo incurre en cargos cuando necesita implementar agentes de Console en su nube para garantizar la conectividad con sus sistemas de almacenamiento o servicios de datos de NetApp . Sin embargo, algunos servicios de datos de NetApp accesibles desde la consola requieren licencia o suscripción.

Obtenga más información sobre el https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["Consola de NetApp"] .



== Funciones

* Administrar volúmenes NFS y CIFS
* Acceda a ONTAP System Manager para cualquier clúster administrado a través de la consola
* Obtenga observabilidad de la salud y el rendimiento con análisis y control
* Utilice servicios de datos para replicar, realizar copias de seguridad, escanear, clasificar y organizar datos en niveles.
* Ver información sobre el estado del contrato de hardware y software en la consola




== Costo

Podría haber un costo asociado, pero depende de lo siguiente:

* Donde implementa un agente de consola para descubrir y administrar sus clústeres.
+
Puede instalar un agente de consola en la nube o en sus instalaciones.  La instalación de un agente de consola en la nube implica costos.

* Ya sea que utilice servicios de datos de NetApp como NetApp Backup and Recovery, NetApp Ransomware Resilience, etc.

